version: '3.8'

services:
  app:
    build:
      context: .
      args:
        VITE_BACKEND_SERVICE_URL: ${VITE_BACKEND_SERVICE_URL}
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_SERVICE_URL=${VITE_BACKEND_SERVICE_URL}